Merge pull request Client ui #3 from Joe-Sendra/client-ui
* Includes Bootstrap and jQuery

* Navbar and Register components created

* Add bootstrap theme and updated home page

* Register user adds user to database

* Login and Logout using Local Storage

* Remove logout component - not needed

* Remove unused fake api data

* Remove logout components from user and admin

* Resolve error TS2339

* Add role to user, route to appropriate dashboard

* Use config file for api server/port

* Use JWT for authentication and route using guards

* Indicate login error for incorrect credentials